"use client";

import { useState } from "react";
import type { RIReportAnalysis, SurveyDataV2 } from "@/lib/survey-types";
import { exportReportToDocx } from "@/lib/docx-export";
import ReportToolbar from "./ReportToolbar";
import CoverPage from "./CoverPage";
import TableOfContents from "./TableOfContents";
import PropertySummary from "./PropertySummary";
import ReportSection from "./ReportSection";
import ComplianceTable from "./ComplianceTable";
import PhotoAppendix from "./PhotoAppendix";
import RiskScoreGauge from "@/components/RiskScoreGauge";
import {
  Target,
  AlertTriangle,
  Clock,
  Shield,
} from "lucide-react";

interface RIReportProps {
  analysis: RIReportAnalysis;
  surveyData: SurveyDataV2;
  onBack: () => void;
  analystName?: string;
  analystDate?: string;
}

export default function RIReport({ analysis, surveyData, onBack, analystName, analystDate }: RIReportProps) {
  const reportRef = `NTRU-${Date.now().toString(36).toUpperCase()}`;
  const filename = `NTRU-RI-Report-${(surveyData.sectionA.address || "survey").replace(/[^a-zA-Z0-9]/g, "-")}-${new Date().toISOString().split("T")[0]}.pdf`;
  const wordFilename = filename.replace(/\.pdf$/, ".docx");

  const handleExportWord = async () => {
    await exportReportToDocx(analysis, surveyData, reportRef, wordFilename, analystName, analystDate);
  };

  const tocItems = [
    { id: "section-summary", label: "Executive Summary" },
    { id: "section-property", label: "Property Summary" },
    ...analysis.sections.map((s) => ({
      id: `section-${s.sectionId}`,
      label: `Section ${s.sectionId}: ${s.title}`,
      score: s.riskScore,
      grade: s.riskGrade,
    })),
    { id: "section-compliance", label: "Compliance Summary" },
    { id: "section-recommendations", label: "Priority Recommendations" },
    ...(surveyData.photos.length > 0
      ? [{ id: "section-photos", label: "Photo Evidence" }]
      : []),
  ];

  const [brokerNotes, setBrokerNotes] = useState("");

  // Group recommendations by timeframe
  const recGroups = [
    { key: "Immediate", label: "Immediate Action", color: "#ef4444", bg: "rgba(239,68,68,0.06)", border: "rgba(239,68,68,0.15)" },
    { key: "30 days", label: "Within 30 Days", color: "#f97316", bg: "rgba(249,115,22,0.06)", border: "rgba(249,115,22,0.15)" },
    { key: "90 days", label: "Within 90 Days", color: "#f59e0b", bg: "rgba(245,158,11,0.06)", border: "rgba(245,158,11,0.15)" },
    { key: "12 months", label: "Within 12 Months", color: "#3b82f6", bg: "rgba(59,130,246,0.06)", border: "rgba(59,130,246,0.15)" },
  ];

  return (
    <div className="min-h-screen bg-gray-50/50">
      <ReportToolbar
        reportId="ri-report"
        title={`NTRU RI Report - ${surveyData.sectionA.address}`}
        shareText={`Property risk inspection for ${surveyData.sectionA.address}. Overall risk: ${analysis.overallRiskScore}/100 (${analysis.overallRiskGrade}).`}
        onBack={onBack}
        filename={filename}
        onExportWord={handleExportWord}
      />

      {analystName && (
        <div className="print:hidden bg-purple-50 border-b border-purple-100">
          <div className="mx-auto max-w-5xl px-4 py-2 flex items-center justify-center gap-3 text-xs text-[#3D1556]">
            <span className="font-semibold">Report generated by: {analystName}</span>
            <span className="text-purple-300">&middot;</span>
            <span>{analystDate || new Date().toISOString().split("T")[0]}</span>
          </div>
        </div>
      )}

      <div id="ri-report" className="mx-auto max-w-5xl px-4 py-10 space-y-10">
        {/* ═══ 1. Cover Page ═══ */}
        <div className="page-break-after">
          <CoverPage surveyData={surveyData} reportRef={reportRef} />
        </div>

        {/* ═══ 2. Table of Contents ═══ */}
        <div className="page-break-after">
          <TableOfContents items={tocItems} />
        </div>

        {/* ═══ 3. Executive Summary ═══ */}
        <div id="section-summary" className="rounded-3xl border border-gray-200 bg-[var(--surface)] p-6 sm:p-10 break-inside-avoid page-break-after shadow-sm">
          <div className="flex items-center gap-3 mb-8">
            <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-gradient-to-br from-slate-700 to-slate-900">
              <Shield className="h-5 w-5 text-white" />
            </div>
            <h2 className="text-xl font-black text-[var(--foreground)] tracking-tight">
              Executive Summary
            </h2>
          </div>

          <div className="flex flex-col items-center gap-10 md:flex-row md:items-start">
            <div className="flex-1">
              <p className="text-[15px] leading-[1.8] text-gray-600">
                {analysis.executiveSummary}
              </p>
              {/* Quick stats */}
              <div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
                {[
                  { label: "Occupancy", value: surveyData.sectionA.occupancy || "\u2014" },
                  { label: "Plot Area", value: surveyData.sectionA.plotArea ? `${surveyData.sectionA.plotArea} sqm` : "\u2014" },
                  { label: "Built Area", value: surveyData.sectionA.constructedArea ? `${surveyData.sectionA.constructedArea} sqm` : "\u2014" },
                  { label: "Floors", value: surveyData.sectionA.numberOfFloors || "\u2014" },
                  { label: "Flood Risk", value: surveyData.sectionA.floodRiskLevel || "\u2014" },
                ].map((stat) => (
                  <div key={stat.label} className="rounded-2xl bg-gray-50 border border-gray-200 p-4 text-center">
                    <p className="text-[10px] font-bold text-[var(--muted)] uppercase tracking-widest">{stat.label}</p>
                    <p className="mt-1.5 text-sm font-bold text-[var(--foreground)]">{stat.value}</p>
                  </div>
                ))}
              </div>
            </div>
            <div className="shrink-0">
              <RiskScoreGauge score={analysis.overallRiskScore} />
            </div>
          </div>
        </div>

        {/* ═══ 4. Property Summary ═══ */}
        <div id="section-property" className="page-break-after">
          <PropertySummary surveyData={surveyData} />
        </div>

        {/* ═══ 5. Section Analysis — each on new page ═══ */}
        {analysis.sections.map((section, index) => (
          <div key={section.sectionId} className="page-break-before">
            <ReportSection section={section} sectionIndex={index} />
          </div>
        ))}

        {/* ═══ 6. Compliance — new page ═══ */}
        <div className="page-break-before">
          <ComplianceTable items={analysis.complianceItems} />
        </div>

        {/* ═══ 7. Priority Recommendations — new page ═══ */}
        <div id="section-recommendations" className="space-y-6 page-break-before">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-gradient-to-br from-amber-500 to-orange-600">
              <Target className="h-5 w-5 text-white" />
            </div>
            <div>
              <h2 className="text-xl font-black text-[var(--foreground)] tracking-tight">
                Recommendations
              </h2>
              <p className="text-xs text-[var(--muted)]">Prioritized action items</p>
            </div>
          </div>

          {recGroups.map((group) => {
            const recs = analysis.recommendations.filter((r) => r.timeframe === group.key);
            if (recs.length === 0) return null;
            return (
              <div key={group.key} className="space-y-2">
                <div className="flex items-center gap-2 px-1">
                  <span className="h-2 w-2 rounded-full" style={{ backgroundColor: group.color }} />
                  <h3 className="text-[11px] font-bold uppercase tracking-widest" style={{ color: group.color }}>
                    {group.label}
                  </h3>
                </div>
                {recs.map((rec) => (
                  <div
                    key={rec.priority}
                    className="flex items-start gap-4 rounded-2xl p-5 break-inside-avoid"
                    style={{ backgroundColor: group.bg, border: `1px solid ${group.border}` }}
                  >
                    <span
                      className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl text-xs font-black text-white"
                      style={{ backgroundColor: group.color }}
                    >
                      {rec.priority}
                    </span>
                    <div className="flex-1 min-w-0">
                      <h4 className="text-sm font-bold text-[var(--foreground)]">{rec.title}</h4>
                      <p className="mt-1 text-sm text-gray-600 leading-relaxed">{rec.description}</p>
                      <div className="mt-2 flex items-center gap-3">
                        <span className="flex items-center gap-1 text-[10px] font-bold text-gray-400 uppercase tracking-wider">
                          <Clock className="h-3 w-3" /> {rec.timeframe}
                        </span>
                        <span className="flex items-center gap-1 text-[10px] font-bold text-gray-400 uppercase tracking-wider">
                          <AlertTriangle className="h-3 w-3" /> Section {rec.section}
                        </span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            );
          })}
        </div>

        {/* ═══ 8. Client / Broker Notes ═══ */}
        <div className="rounded-2xl border border-gray-200 bg-white shadow-sm overflow-hidden break-inside-avoid">
          <div className="px-6 py-4 border-b border-gray-100 bg-gray-50 flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600">
              <Shield className="h-4 w-4 text-white" />
            </div>
            <div>
              <h3 className="text-sm font-black text-[var(--foreground)] tracking-tight">
                Client / Broker Commitment &amp; Requests
              </h3>
              <p className="text-[11px] text-[var(--muted)]">Record any commitments, undertakings or special requests here</p>
            </div>
          </div>
          <div className="p-4">
            <textarea
              value={brokerNotes}
              onChange={(e) => setBrokerNotes(e.target.value)}
              placeholder="Type commitments, undertakings, or special requests here…"
              rows={6}
              className="w-full rounded-xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-800 placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-300 focus:border-indigo-300 resize-y leading-relaxed print:border-gray-300 print:bg-white"
              style={{ minHeight: "120px" }}
            />
          </div>
        </div>

        {/* ═══ 9. Photo Evidence — new page ═══ */}
        <div className="page-break-before">
          <PhotoAppendix photos={surveyData.photos} sections={analysis.sections} />
        </div>

        {/* ═══ 9. Disclaimer Footer ═══ */}
        <div className="rounded-2xl bg-[#1a0a2e] px-8 py-6 text-center break-inside-avoid print-cover-page">
          <p className="text-[10px] font-bold text-white/50 uppercase tracking-widest mb-3">
            Disclaimer
          </p>
          <p className="text-[11px] text-white/30 max-w-2xl mx-auto leading-relaxed">
            This Risk Inspection Report has been prepared on a provisional basis using AI-powered image analysis and surveyor-provided input data. The findings, observations, risk scores, and recommendations contained herein are indicative only and do not constitute a formal risk assessment, professional survey opinion, or underwriting advice of any kind.
          </p>
          <p className="text-[11px] text-white/30 max-w-2xl mx-auto leading-relaxed mt-2">
            NTRU / NTRU RiskLens, its officers, employees, and technology partners expressly disclaim all liability for any loss, damage, or consequence arising directly or indirectly from reliance on the contents of this report. The information herein may be incomplete, subject to change, and has not been independently verified.
          </p>
          <div className="mt-3 flex items-center justify-center gap-4 text-[10px] text-white/20">
            <span>Ref: {reportRef}</span>
            <span>&middot;</span>
            <span>
              {new Date().toLocaleDateString("en-US", {
                year: "numeric",
                month: "long",
                day: "numeric",
              })}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
