import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  HeadingLevel,
  BorderStyle,
  ShadingType,
  PageBreak,
  Header,
  Footer,
  TabStopType,
  TabStopPosition,
} from "docx";
import { saveAs } from "file-saver";
import type { RIReportAnalysis, SurveyDataV2 } from "./survey-types";

// NTRU brand purple
const PURPLE = "3D1556";
const PURPLE_LIGHT = "5B2D8E";
const GRAY = "64748B";
const GRAY_LIGHT = "F1F5F9";
const WHITE = "FFFFFF";

// Severity → color mapping
const severityColor: Record<string, string> = {
  Critical: "DC2626",
  High: "EA580C",
  Medium: "D97706",
  Low: "2563EB",
};

const statusColor: Record<string, string> = {
  Compliant: "16A34A",
  "Non-Compliant": "DC2626",
  "Partially Compliant": "D97706",
  "N/A": "64748B",
};

function gradeColor(grade: string): string {
  if (grade === "Low") return "16A34A";
  if (grade === "Moderate") return "D97706";
  if (grade === "High") return "EA580C";
  return "DC2626"; // Critical
}

// ─── Helper: shaded cell for table headers ───
function headerCell(text: string, width?: number): TableCell {
  return new TableCell({
    width: width ? { size: width, type: WidthType.PERCENTAGE } : undefined,
    shading: { type: ShadingType.SOLID, color: PURPLE, fill: PURPLE },
    children: [
      new Paragraph({
        spacing: { before: 40, after: 40 },
        children: [new TextRun({ text, bold: true, color: WHITE, size: 18, font: "Calibri" })],
      }),
    ],
  });
}

function bodyCell(text: string, width?: number, color?: string): TableCell {
  return new TableCell({
    width: width ? { size: width, type: WidthType.PERCENTAGE } : undefined,
    children: [
      new Paragraph({
        spacing: { before: 30, after: 30 },
        children: [new TextRun({ text, size: 18, font: "Calibri", color: color || "0F172A" })],
      }),
    ],
  });
}

// ─── Main Export Function ───
export async function exportReportToDocx(
  analysis: RIReportAnalysis,
  surveyData: SurveyDataV2,
  reportRef: string,
  filename: string
): Promise<void> {
  const { sectionA } = surveyData;
  const date = new Date(sectionA.dateOfSurvey || Date.now()).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const doc = new Document({
    creator: "NTRU RiskLens",
    title: `NTRU RI Report - ${sectionA.address}`,
    description: "Risk Inspection Report generated by NTRU RiskLens",
    styles: {
      default: {
        document: {
          run: { font: "Calibri", size: 20 },
        },
        heading1: {
          run: { font: "Calibri", size: 32, bold: true, color: PURPLE },
          paragraph: { spacing: { before: 360, after: 120 } },
        },
        heading2: {
          run: { font: "Calibri", size: 26, bold: true, color: PURPLE_LIGHT },
          paragraph: { spacing: { before: 240, after: 80 } },
        },
      },
    },
    sections: [
      // ═══════════════════════════════════════════
      // COVER PAGE
      // ═══════════════════════════════════════════
      {
        properties: {
          page: {
            margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 },
          },
        },
        children: [
          // Spacer
          new Paragraph({ spacing: { before: 2000 } }),

          // NTRU
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({ text: "NTRU", bold: true, size: 72, color: PURPLE, font: "Calibri" }),
            ],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 120 },
            children: [
              new TextRun({
                text: "NewTech Reinsurance & Underwriting Limited",
                size: 22,
                color: GRAY,
                font: "Calibri",
              }),
            ],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 600 },
            children: [
              new TextRun({
                text: "Empowering Risk Solutions",
                italics: true,
                size: 20,
                color: PURPLE_LIGHT,
                font: "Calibri",
              }),
            ],
          }),

          // Title
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 80 },
            children: [
              new TextRun({ text: "RISK INSPECTION REPORT", bold: true, size: 40, color: PURPLE, font: "Calibri" }),
            ],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 40 },
            children: [
              new TextRun({ text: "Confidential", size: 20, color: GRAY, font: "Calibri" }),
            ],
          }),

          // Spacer
          new Paragraph({ spacing: { before: 600 } }),

          // Property details table
          new Table({
            width: { size: 70, type: WidthType.PERCENTAGE },
            alignment: AlignmentType.CENTER,
            rows: [
              new TableRow({
                children: [
                  headerCell("Insured", 30),
                  bodyCell(sectionA.insuredName || "—", 70),
                ],
              }),
              new TableRow({
                children: [
                  headerCell("Property Address", 30),
                  bodyCell(sectionA.address || "—", 70),
                ],
              }),
              new TableRow({
                children: [
                  headerCell("Date of Inspection", 30),
                  bodyCell(date, 70),
                ],
              }),
              new TableRow({
                children: [
                  headerCell("Surveyor", 30),
                  bodyCell(sectionA.surveyorName || "—", 70),
                ],
              }),
              new TableRow({
                children: [
                  headerCell("Report Reference", 30),
                  bodyCell(reportRef, 70),
                ],
              }),
              new TableRow({
                children: [
                  headerCell("Overall Risk", 30),
                  bodyCell(
                    `${analysis.overallRiskScore}/100 (${analysis.overallRiskGrade})`,
                    70,
                    gradeColor(analysis.overallRiskGrade)
                  ),
                ],
              }),
            ],
          }),
        ],
      },

      // ═══════════════════════════════════════════
      // REPORT BODY
      // ═══════════════════════════════════════════
      {
        properties: {
          page: {
            margin: { top: 1440, bottom: 1440, left: 1200, right: 1200 },
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                tabStops: [{ type: TabStopType.RIGHT, position: TabStopPosition.MAX }],
                children: [
                  new TextRun({ text: "NTRU  ·  Confidential", size: 14, color: GRAY, font: "Calibri" }),
                  new TextRun({ text: "\t", size: 14 }),
                  new TextRun({ text: `Ref: ${reportRef}`, size: 14, color: GRAY, font: "Calibri" }),
                ],
                border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: PURPLE_LIGHT } },
                spacing: { after: 200 },
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: "NTRU RiskLens — AI-Powered Risk Inspection Report",
                    size: 14,
                    color: GRAY,
                    font: "Calibri",
                  }),
                ],
              }),
            ],
          }),
        },
        children: [
          // ── EXECUTIVE SUMMARY ──
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: "Executive Summary", bold: true, size: 32, color: PURPLE, font: "Calibri" })],
          }),
          new Paragraph({
            spacing: { after: 120 },
            children: [
              new TextRun({ text: `Overall Risk Score: `, size: 22, font: "Calibri" }),
              new TextRun({
                text: `${analysis.overallRiskScore}/100 (${analysis.overallRiskGrade})`,
                bold: true,
                size: 22,
                color: gradeColor(analysis.overallRiskGrade),
                font: "Calibri",
              }),
            ],
          }),
          new Paragraph({
            spacing: { after: 200 },
            children: [new TextRun({ text: analysis.executiveSummary, size: 20, font: "Calibri" })],
          }),

          // Quick stats table
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  headerCell("Occupancy"),
                  headerCell("Plot Area"),
                  headerCell("Built Area"),
                  headerCell("Floors"),
                  headerCell("Flood Risk"),
                ],
              }),
              new TableRow({
                children: [
                  bodyCell(sectionA.occupancy || "—"),
                  bodyCell(sectionA.plotArea ? `${sectionA.plotArea} sqm` : "—"),
                  bodyCell(sectionA.constructedArea ? `${sectionA.constructedArea} sqm` : "—"),
                  bodyCell(String(sectionA.numberOfFloors || "—")),
                  bodyCell(sectionA.floodRiskLevel || "—"),
                ],
              }),
            ],
          }),

          // ── SECTION ANALYSES ──
          ...analysis.sections.flatMap((section) => [
            new Paragraph({ children: [new PageBreak()] }),
            new Paragraph({
              heading: HeadingLevel.HEADING_1,
              children: [
                new TextRun({
                  text: `Section ${section.sectionId}: ${section.title}`,
                  bold: true,
                  size: 32,
                  color: PURPLE,
                  font: "Calibri",
                }),
              ],
            }),
            new Paragraph({
              spacing: { after: 40 },
              children: [
                new TextRun({ text: "Risk Score: ", size: 20, font: "Calibri" }),
                new TextRun({
                  text: `${section.riskScore}/100 (${section.riskGrade})`,
                  bold: true,
                  size: 20,
                  color: gradeColor(section.riskGrade),
                  font: "Calibri",
                }),
              ],
            }),
            new Paragraph({
              spacing: { after: 200 },
              children: [new TextRun({ text: section.narrative, size: 20, font: "Calibri" })],
            }),

            // Findings heading
            new Paragraph({
              heading: HeadingLevel.HEADING_2,
              children: [new TextRun({ text: "Findings", bold: true, size: 24, color: PURPLE_LIGHT, font: "Calibri" })],
            }),

            // Findings table
            new Table({
              width: { size: 100, type: WidthType.PERCENTAGE },
              rows: [
                new TableRow({
                  children: [
                    headerCell("Finding", 25),
                    headerCell("Severity", 12),
                    headerCell("Description", 33),
                    headerCell("Recommendation", 30),
                  ],
                }),
                ...section.findings.map(
                  (f) =>
                    new TableRow({
                      children: [
                        bodyCell(f.title, 25),
                        bodyCell(f.severity, 12, severityColor[f.severity] || "0F172A"),
                        bodyCell(f.description, 33),
                        bodyCell(f.recommendation, 30),
                      ],
                    })
                ),
              ],
            }),

            // Positives
            ...(section.positives.length > 0
              ? [
                  new Paragraph({
                    spacing: { before: 200 },
                    heading: HeadingLevel.HEADING_2,
                    children: [new TextRun({ text: "Positives", bold: true, size: 24, color: "16A34A", font: "Calibri" })],
                  }),
                  ...section.positives.map(
                    (p) =>
                      new Paragraph({
                        spacing: { before: 40, after: 40 },
                        children: [
                          new TextRun({ text: "✓ ", bold: true, color: "16A34A", size: 20, font: "Calibri" }),
                          new TextRun({ text: p, size: 20, font: "Calibri" }),
                        ],
                      })
                  ),
                ]
              : []),
          ]),

          // ── COMPLIANCE TABLE ──
          new Paragraph({ children: [new PageBreak()] }),
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: "Compliance Summary", bold: true, size: 32, color: PURPLE, font: "Calibri" })],
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  headerCell("Category", 25),
                  headerCell("Item", 30),
                  headerCell("Status", 20),
                  headerCell("Remarks", 25),
                ],
              }),
              ...analysis.complianceItems.map(
                (item) =>
                  new TableRow({
                    children: [
                      bodyCell(item.category, 25),
                      bodyCell(item.item, 30),
                      bodyCell(item.status, 20, statusColor[item.status] || "0F172A"),
                      bodyCell(item.remarks, 25),
                    ],
                  })
              ),
            ],
          }),

          // ── RECOMMENDATIONS ──
          new Paragraph({ children: [new PageBreak()] }),
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [
              new TextRun({ text: "Priority Recommendations", bold: true, size: 32, color: PURPLE, font: "Calibri" }),
            ],
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  headerCell("#", 8),
                  headerCell("Recommendation", 35),
                  headerCell("Description", 30),
                  headerCell("Section", 12),
                  headerCell("Timeframe", 15),
                ],
              }),
              ...analysis.recommendations.map(
                (rec) =>
                  new TableRow({
                    children: [
                      bodyCell(String(rec.priority), 8),
                      bodyCell(rec.title, 35),
                      bodyCell(rec.description, 30),
                      bodyCell(`Section ${rec.section}`, 12),
                      bodyCell(rec.timeframe, 15),
                    ],
                  })
              ),
            ],
          }),

          // ── DISCLAIMER ──
          new Paragraph({ spacing: { before: 600 } }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 80 },
            shading: { type: ShadingType.SOLID, color: GRAY_LIGHT, fill: GRAY_LIGHT },
            children: [
              new TextRun({
                text: "DISCLAIMER",
                bold: true,
                size: 16,
                color: GRAY,
                font: "Calibri",
              }),
            ],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            shading: { type: ShadingType.SOLID, color: GRAY_LIGHT, fill: GRAY_LIGHT },
            children: [
              new TextRun({
                text: "This Risk Inspection Report has been prepared on a provisional basis using AI-powered image analysis and surveyor-provided input data. The findings, observations, risk scores, and recommendations contained herein are indicative only and do not constitute a formal risk assessment, professional survey opinion, or underwriting advice of any kind.",
                size: 16,
                color: GRAY,
                font: "Calibri",
              }),
            ],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { before: 80 },
            shading: { type: ShadingType.SOLID, color: GRAY_LIGHT, fill: GRAY_LIGHT },
            children: [
              new TextRun({
                text: "NTRU / NTRU RiskLens, its officers, employees, and technology partners expressly disclaim all liability for any loss, damage, or consequence arising directly or indirectly from reliance on the contents of this report. The information herein may be incomplete, subject to change, and has not been independently verified.",
                size: 16,
                color: GRAY,
                font: "Calibri",
              }),
            ],
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, filename);
}
